### ISSUE TITLE
How to forecast multiple parameter

### ISSUE THREAD

**Issue by Sharathmk99** [detrevid/predictionio-load-forecasting#1]
Hi,
How to forecast multiple parameters like, as of now you are forecasting only one parameter i.e energy consumption, but i want to forecast multiple parameter like energy efficiency etc... 
How to alter your code to meet my requirement.
Thanks

**Comment by detrevid** [comment]
Hello,
If you want to use the LinearRegressionWithSGD from Spark (used in this template), probably the easiest way would be to do the same thing for each parameter that you can see has been done here for energy consumption. So:
1. Add uploading the new parameter in DataSource.scala (you probably should add new field to ConsumptionEvent class).
2. Add preparing data for the new parameter in Preparator.scala (you probably should add new LabeledPoint (that corresponds to the new parameter) for each circuit id in PreparedData class).
3. For each circuit id create new LinearRegressionModel for the new parameter (the same way it is done now for energyConsumption) in Algorithm.scala. You are going to end-up with list of regression models for each circuit id - every model on the list will correspond to a parameter. 
4. Probably gonna need to make some other changes, among others: add a new field to PredictedResult and ActualResult in Engine.scala.

That's just a draft of example solution, there are probably many other ways of getting the result you are looking for.
Hope this helped.

**Comment by Sharathmk99** [comment]
Yes thank you.
